export default {
	EVENT_STICKER_MOVE:          'EVENT_STICKER_MOVE',
	EVENT_STICKER_CREATE:        'EVENT_STICKER_CREATE',
	EVENT_STICKER_EDIT:          'EVENT_STICKER_EDIT',
	EVENT_STICKER_EDIT_DISMISS:  'EVENT_STICKER_EDIT_DISMISS',
	EVENT_STICKER_EDIT_COMPLETE: 'EVENT_STICKER_EDIT_COMPLETE',
};