export default {
	EVENT_STICKERS_LOADING:      'EVENT_STICKERS_LOADING',
	EVENT_STICKERS_LOADED:       'EVENT_STICKERS_LOADED',
	EVENT_STICKER_MOVE:          'EVENT_STICKER_MOVE',
	EVENT_STICKER_CREATE:        'EVENT_STICKER_CREATE',
	EVENT_STICKER_EDIT:          'EVENT_STICKER_EDIT',
	EVENT_STICKER_EDIT_DISMISS:  'EVENT_STICKER_EDIT_DISMISS',
	EVENT_STICKER_EDIT_COMPLETE: 'EVENT_STICKER_EDIT_COMPLETE',
	EVENT_STICKER_DELETE:        'EVENT_STICKER_DELETE',
	EVENT_SHOW_ERROR:            'EVENT_SHOW_ERROR',
};